/**
 * Generates a docker-compose override file with N p2p-profile indexer nodes
 * (1 seed + N-1 peers) for exercising the "10+ indexer nodes" acceptance
 * criterion (docs/P2P_INDEXER_DESIGN.md §7), beyond the 3 nodes hand-written
 * in docker-compose.yml.
 *
 * Usage:
 *   ts-node scripts/gen-p2p-compose.ts 10 > docker-compose.p2p.generated.yml
 *   docker compose -f docker-compose.yml -f docker-compose.p2p.generated.yml --profile p2p up -d
 *
 * Each generated node gets its own Postgres (matching the hand-written
 * seed/peer1/peer2 topology) and a distinct host port starting at 3010.
 */

const count = parseInt(process.argv[2] ?? '10', 10);
if (!Number.isFinite(count) || count < 1 || count > 100) {
  console.error('Usage: ts-node scripts/gen-p2p-compose.ts <nodeCount 1-100>');
  process.exit(1);
}

const BASE_PORT = 3010;

function dbService(name: string): string {
  return `  db-testnet-p2p-gen-${name}:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: soroban_testnet_p2p_gen_${name}
    volumes:
      - pgdata-testnet-p2p-gen-${name}:/var/lib/postgresql/data
    healthcheck: *db-healthcheck
    deploy:
      resources: *db-resources
    logging: *logging
    profiles: [p2p]
`;
}

function nodeService(name: string, port: number, isSeed: boolean): string {
  const dependsOnSeed = isSeed
    ? ''
    : `      indexer-testnet-p2p-gen-seed:
        condition: service_started
`;
  return `  indexer-testnet-p2p-gen-${name}:
    <<: [*app-build, *security]
    restart: unless-stopped
    ports:
      - '${port}:${port}'
    environment:
      STELLAR_NETWORK: testnet
      PORT: ${port}
      TESTNET_DATABASE_URL: postgresql://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@db-testnet-p2p-gen-${name}:5432/soroban_testnet_p2p_gen_${name}
      DATABASE_URL: postgresql://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@db-testnet-p2p-gen-${name}:5432/soroban_testnet_p2p_gen_${name}
      TESTNET_RPC_URL: https://soroban-testnet.stellar.org
      TESTNET_HORIZON_URL: https://horizon-testnet.stellar.org
      TESTNET_PASSPHRASE: "Test SDF Network ; September 2015"
      P2P_ENABLED: 'true'
      P2P_MDNS_ENABLED: 'true'
      ${isSeed ? "P2P_IS_RELAY_SERVER: 'true'\n      " : ''}P2P_LISTEN_ADDR: /ip4/0.0.0.0/tcp/4001
      P2P_IDENTITY_PATH: /app/data/p2p/testnet/identity.key
      P2P_CHALLENGE_INTERVAL_MS: '15000'
    volumes:
      - p2p-identity-gen-${name}:/app/data/p2p
    depends_on:
      db-testnet-p2p-gen-${name}:
        condition: service_healthy
${dependsOnSeed}    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:${port}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources: *indexer-resources
    logging: *logging
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    profiles: [p2p]
`;
}

const names = ['seed', ...Array.from({ length: count - 1 }, (_, i) => `peer${i + 1}`)];

const lines: string[] = [
  '# Generated by scripts/gen-p2p-compose.ts — do not hand-edit.',
  `# ${count}-node local P2P swarm for the acceptance-criteria test harness.`,
  '',
  'x-app-build: &app-build',
  '  build: .',
  '',
  'x-security: &security',
  '  cap_drop:',
  '    - ALL',
  '  cap_add:',
  '    - NET_BIND_SERVICE',
  '  read_only: true',
  '  tmpfs:',
  '    - /tmp:noexec,nosuid,size=100M',
  '  security_opt:',
  '    - seccomp:./seccomp/node.json',
  '',
  'x-db-healthcheck: &db-healthcheck',
  "  test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']",
  '  interval: 5s',
  '  timeout: 5s',
  '  retries: 5',
  '',
  'x-logging: &logging',
  '  driver: json-file',
  '  options:',
  "    max-size: '10m'",
  "    max-file: '3'",
  '',
  'x-db-resources: &db-resources',
  '  limits:',
  "    cpus: '0.50'",
  '    memory: 512M',
  '  reservations:',
  "    cpus: '0.10'",
  '    memory: 128M',
  '',
  'x-indexer-resources: &indexer-resources',
  '  limits:',
  "    cpus: '0.50'",
  '    memory: 256M',
  '  reservations:',
  "    cpus: '0.05'",
  '    memory: 64M',
  '',
  'services:',
];

names.forEach((name, i) => {
  lines.push(dbService(name));
  lines.push(nodeService(name, BASE_PORT + i, name === 'seed'));
});

lines.push('volumes:');
for (const name of names) {
  lines.push(`  pgdata-testnet-p2p-gen-${name}:`);
  lines.push(`  p2p-identity-gen-${name}:`);
}

console.log(lines.join('\n'));
